### ISSUE TITLE
Different definition of the joint in MPII and Human3.6M

### ISSUE THREAD

**Issue by DeepRunner** [xingyizhou/pytorch-pose-hg-3d#11]
The definition of some joints in MPII and Human3.6M is quite different(e.g. the left/right hip,  left/right foot). 
For example, a) the distance between left and right hip is longer on Human3.6M. b) The left/right foot in Human3.6M is  behind of the foot in MPII actually.
![1](https://user-images.githubusercontent.com/37103809/38456540-44946db6-3a75-11e8-9a00-311a8fc176e6.png)
![2](https://user-images.githubusercontent.com/37103809/38456541-48a74810-3a75-11e8-9a5a-d210cdab7c7b.png)
![3](https://user-images.githubusercontent.com/37103809/38456542-4a9528cc-3a75-11e8-9d2a-8a4b1efe2844.png)

I guess these subtle difference in 2d positions may lead serious error for depth regression
The step 2 and 3 is trained by mixed data. 
A) Will this make the network learn a  contradictory 2d prediction?
B) Will this make less sense for weak training of depth regression on MPII (because depth regression across the two dataset is performed on different joints actually, but the network don't know this difference)

**Comment by xingyizhou** [comment]
Hi, 
  I also noted the difference but it seems inevitable since the MPII dataset itself contains some inconsistency in hips. I don't think the subtle difference is so important, as the results look good for me. If you want to try, a preliminary idea is to manually modify the annotation in H36M based on the 3D bone length ratios to match MPII.
