### ISSUE TITLE
A request: MPII-INF-3DHP

### ISSUE THREAD

**Issue by bloodymeli** [xingyizhou/pytorch-pose-hg-3d#12]
Hi Xingyi.

Can you please make available either the post-processed MPII-INF-3DHP or the script you have used in order to pre-process it?

Thanks!

**Comment by xingyizhou** [comment]
Hi, 
  The scripts you want are available in the lua torch repo (https://github.com/xingyizhou/pose-hg-3d/blob/master/src/Tools/GetMPI-INF-3D.py , https://github.com/xingyizhou/pose-hg-3d/blob/master/src/util/dataset/fusion.lua#L126 , and https://github.com/xingyizhou/pose-hg-3d/blob/master/src/util/pose-hgreg-3d.lua#L203 ) . I haven't found time to convert that part to pytorch since it is not used in training. A problem of the lua code is that I was using a pre-release version of 3DHP,  for that this paper published before the 3DHP paper. I haven't re-evaluated the performance on the officially released 3DHP dataset yet (and it is in a low priority comparing to other deadlines I am rushing for). You can follow my lua torch code to evaluate on the official 3DHP dataset yourself.
