### ISSUE TITLE
What's the meaning of 'scale' in mpii dataset?

### ISSUE THREAD

**Issue by EthanGuan** [xingyizhou/pytorch-pose-hg-3d#2]
if I use my own dataset, every image is 640 * 480, what's the value of scale should I set it to?

**Comment by xingyizhou** [comment]
Hi EthanGuan, 
  Thanks for your interest in this project. The 'scale' in the mpii dataset is provided as an annotation, it is the square-shape human bounding size. It is dependent on the human bounding box size, not just the input image size. But it is safe to just set the scale to 640 and center at (320, 240).

**Comment by bwuzhang** [comment]
Would you please elaborate on this? How do I get bounding box given center and scale?

**Comment by xingyizhou** [comment]
The upper-left and bottom-right coordinates of bounding box are (center[0] - scale / 2, center[1] - scale / 2), (center[0] + scale / 2, center[1] + scale / 2).

**Comment by bwuzhang** [comment]
I guess by saying 'scale' you mean '200 * scale'. I did try this but I got
some absurd annotation...

On Feb 28, 2018 9:14 PM, "Xingyi Zhou" <notifications@github.com> wrote:

The upper-left and bottom-right coordinates of bounding box are (center[0]
- scale / 2, center[1] - scale / 2), (center[0] + scale / 2, center[1] +
scale / 2).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/xingyizhou/pytorch-pose-hg-3d/issues/2#issuecomment-369451278>,
or mute the thread

**Comment by xingyizhou** [comment]
Yes, it is '200 x scale' based on Newell's hourglass implementation. What's the following question?
